version: '3.8'

services:
  db:
    image: postgres:13.3-alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - rd_data:/data
    networks:
      - backend

volumes:
  pg_data:
  rd_data:

networks:
  backend:
    name: backend